### PR TITLE
fixes #116

### LINKED ISSUE #116: always respect dateClassObj when constructing new date objects
hi,
I already reported a bug at

https://bugs.dojotoolkit.org/ticket/18796

in the latest dojo-release, dojox/calendar/ViewBase._setupDayRefresh doesn't use newDate() to construct a date-instance.
is it possible to fix this for the upcomming 1.11 release?

### PR DESCRIPTION
**Pull request by gerpres**

### CODE REVIEW

**Comment by wkeese** [comment]
Also hardcoded in ViewBase#_setupDayRefresh() ?

**Comment by dylans** [comment]
@damiengarbarino any chance of landing this week for Dojo 1.11?

**Comment by gerpres** [comment]
this should've been an easy one - since the rc5 landed a view days ago, I'm
now afraid it won't be included :/
why?

Dylan Schiemann <notifications@github.com> schrieb am Di., 8. März 2016 um
02:12 Uhr:

**Comment by dylans** [comment]
@gerpres I agree, but I've not been able to get @damiengarbarino's attention, so it will have to wait until 1.11.1 most likely.

**Comment by gerpres** [comment]
since 1.11.1 is already live....any plans for 1.11.2?

**Comment by damiengarbarino** [comment]
Sorry guys, I changed the email adress on GH and I haven't got the notifications... a filter a bit too eager to filter out I guess.
Anyway, let me merge this properly.

**Comment by damiengarbarino** [comment]
Manually merged in a1e3dcbaac7c4f182cdd63770bbe25906c5686e7

**Pull request closed without merging**
